### ISSUE TITLE
問題のきちんとした仕様を決める

### ISSUE THREAD

**Issue by hanazuki** [pepabo/sekigae2015#1]
ただ名前をシャッフルするだけお題だと去年のコードと代わり映えのしないものが集まるだけになりそうなので，入出力の仕様を決めてはどうでしょうか．もっと面白くなると思います！

**Comment by hanazuki** [comment]
案:
- 名前の一覧がテキストファイルであたえられるので，プログラムはそれを読み込むことにする

```
@Joe-noh
@alotofwe
@hanazuki
@komaji
@orzup
@takuminnnn
```
- 名前をシャッフルして，2行に半分ずつ出力する．ただし，上下に並ぶ名前は左端を揃える．

```
@Joe-noh @orzup      @hanazuki
@komaji  @takuminnnn @alotofwe
```

**Comment by Joe-noh** [comment]
名前と名前の区切りはどうしましょう？問題の本質から外れるでしょうか？

**Comment by orzup** [comment]
おっくん側の席とかひろやんさん側の席とかもあるとわかりやすそう:eyes:

**Comment by hfm** [comment]
> おっくん側の席とかひろやんさん側の席とかもあるとわかりやすそう:eyes:

よーしあらみそ任せたいい感じによろしく :fire:

**Comment by hanazuki** [comment]
@Joe-noh 
区切り線なんかを出力するようにしても，本質的にやることは変わらないと思うので，好みの問題じゃないでしょうか．
わたしはシンプルな方がすきです！
